name: Android Build OG
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@main
        with:
          ndk-version: r21e

      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Installing Libraries
        run: |
          mkdir -p ~/haxelib
          haxelib setup ~/haxelib
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0
          haxelib install flixel 4.11.0
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons 3.0.2
          haxelib git hxCodec https://github.com/SPLCoding/hxCodec-but-it-works-xd.git
          haxelib git linc_luajit https://github.com/Sirox228/linc_luajit
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib install hxcpp-debug-server
          haxelib list

      - name: Configure Android
        run: |
          haxelib run lime setup android -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Building
        run: haxelib run lime build android -final -v

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: FNF-Android-Build
          path: export/release/android/bin/*.apk
