name: Android Build OG
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        run: |
          mkdir -p $ANDROID_HOME
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-*.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          rm commandlinetools-linux-*.zip
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-33"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;33.0.1"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platform-tools"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "ndk;25.1.8937393"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Setup Haxe
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://haxe.org/website-content/downloads/4.2.5/downloads/haxe-4.2.5-linux64.tar.gz
          sudo tar -xvf haxe-4.2.5-linux64.tar.gz -C /usr/local
          sudo ln -s /usr/local/haxe-4.2.5 /usr/local/haxe
          sudo ln -s /usr/local/haxe/haxe /usr/local/bin/haxe
          sudo ln -s /usr/local/haxe/haxelib /usr/local/bin/haxelib
          mkdir -p ~/haxelib
          haxelib setup ~/haxelib --always
          rm haxe-4.2.5-linux64.tar.gz

      - name: Installing Libraries
        run: |
          haxelib --global install hxcpp 4.2.1 --quiet
          haxelib --global install lime 8.0.1
          haxelib --global install openfl 9.2.1
          haxelib --global install flixel 5.4.0
          haxelib --global install flixel-tools
          haxelib --global install flixel-ui 2.6.0
          haxelib --global install flixel-addons 3.0.2
          haxelib --global git hxCodec https://github.com/polybiusproxy/hxCodec.git
          cd $HOME/haxelib/hxCodec/git
          sed -i '467s/(cast)/(cast).toInt()/' src/vlc/VLCBitmap.hx
          haxelib --global git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib --global install hscript 2.5.0
          haxelib --global git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib --global install hxcpp-debug-server
          haxelib list

      - name: Configure Android
        run: |
          haxelib --global run lime setup android -y
          haxelib --global run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib --global run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib --global run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib --global run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: $ANDROID_HOME/ndk/25.1.8937393

      - name: Building
        run: haxelib --global run lime build android -final -v -Dv2

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FNF-Android-Build
          path: export/release/android/bin/*.apk
